export interface GrupoTribunal {
  corte: string
  tribunales: string[]
}

export const TRIBUNALES: GrupoTribunal[] = [
  {
    corte: 'C.A. de Arica',
    tribunales: [
      '1° Juzgado de Letras de Arica',
      '1° Juzgado de Letras de Arica ex 4°',
      '2° Juzgado de Letras de Arica',
      '2° Juzgado de Letras de Arica ex 4°',
      '3° Juzgado de Letras de Arica',
      '3° Juzgado de Letras de Arica ex 4°',
    ],
  },
  {
    corte: 'C.A. de Iquique',
    tribunales: [
      'Juzgado de Letras y Gar. Pozo Almonte',
      '1° Juzgado de Letras de Iquique',
      '2° Juzgado de Letras de Iquique',
      '3° Juzgado de Letras de Iquique',
    ],
  },
  {
    corte: 'C.A. de Antofagasta',
    tribunales: [
      'Juzgado de Letras Tocopilla',
      'Juzgado de Letras y Gar. de Maria Elena',
      '1° Juzgado de Letras de Calama',
      '2° Juzgado de Letras de Calama',
      '3° Juzgado de Letras de Calama',
      'Juzgado de Letras y Gar. de Taltal',
      '1° Juzgado de Letras Civil de Antofagasta',
      '2° Juzgado de Letras Civil de Antofagasta',
      '3° Juzgado de Letras Civil de Antofagasta',
      '4° Juzgado de Letras Civil de Antofagasta',
      'Juzgado de Letras y Garantía Mejillones',
    ],
  },
  {
    corte: 'C.A. de Copiapó',
    tribunales: [
      'Juzgado de Letras y Gar. de Chañaral',
      'Juzgado de Letras de Diego de Almagro',
      '1° Juzgado de Letras de Copiapó',
      '2° Juzgado de Letras de Copiapó',
      '3° Juzgado de Letras de Copiapó',
      '4° Juzgado de Letras de Copiapó',
      'Juzgado de Letras y Gar. de Freirina',
      '1° Juzgado de Letras de Vallenar',
      '2° Juzgado de Letras de Vallenar',
      'Juzgado de Letras y Gar. de Caldera',
    ],
  },
  {
    corte: 'C.A. de La Serena',
    tribunales: [
      '1° Juzgado de Letras de La Serena',
      '2° Juzgado de Letras de La Serena',
      '3° Juzgado de Letras de La Serena',
      '1° Juzgado de Letras de Coquimbo',
      '2° Juzgado de Letras de Coquimbo',
      '3° Juzgado de Letras de Coquimbo',
      'Juzgado de Letras de Vicuña',
      'Juzgado de Letras y garantía de Andacollo',
      '1° Juzgado de Letras de Ovalle',
      '2° Juzgado de Letras de Ovalle',
      '3° Juzgado de Letras de Ovalle',
      'Juzgado de Letras y Gar. de Combarbalá',
      'Juzgado de letras de Illapel',
      'Juzgado de Letras y Gar. de los Vilos',
    ],
  },
  {
    corte: 'C.A. de Valparaíso',
    tribunales: [
      '1° Juzgado Civil de Valparaíso',
      '2° Juzgado Civil de Valparaíso',
      '3° Juzgado Civil de Valparaíso',
      '4° Juzgado Civil de Valparaíso',
      '5° Juzgado Civil de Valparaíso',  
      '1° Juzgado Civil de Viña del Mar',
      '2° Juzgado Civil de Viña del Mar',
      '3° Juzgado Civil de Viña del Mar',
      '1° Juzgado de Letras de Quilpué',
      '2° Juzgado de Letras de Quilpué',
      'Juzgado de Letras de Villa Alemana',
      'Juzgado de Letras de Casablanca',
      'Juzgado de Letras de la Ligua',
      'Juzgado de Letras y Gar. de Petorca',
      '1° Juzgado de Letras de los Andes',
      '2° Juzgado de Letras de los Andes',
      '1° Juzgado de Letras de San Felipe',
      '1° Juzgado de Letras de San Felipe exp 2°',
      'Juzgado de Letras y Gar. de Putaendo',
      '1° Juzgado de Letras de Quillota',
      '2° Juzgado de Letras de Quillota',
      'Juzgado de Letras de La Calera',
      'Juzgado de Letras de Limache',
      '1° Juzgado de Letras de San Antonio',
      '2° Juzgado de Letras de San Antonio',
      'Juzgado de Letras y Gar. de Isla de Pascua',
      'Juzgado de Letras y Gar. de Quintero',
    ],
  },
  {
    corte: 'C.A. de Rancagua',
    tribunales: [
      '1° Juzgado Civil de Rancagua',
      '2° Juzgado Civil de Rancagua',
      '1° Juzgado de Letras de Rengo',
      'Juzgado de Letras de San Vicente de Tagua Tagua',
      '1° Juzgado de Letras y Gar. de Peumo',
      '1° Juzgado de Letras de San Fernando',
      '2° Juzgado de Letras de San Fernando',
      '1° Juzgado de Letras de Santa Cruz',
      '1° Juzgado de Letras de Santa Cruz ex 2°',
      'Juzgado de Letras y Gar. de Pichilemu',
      'Juzgado de Letras y Gar. de Litueche',
      'Juzgado de Letras y Gar. de Peralillo',
    ],
  },
  {
    corte: 'C.A. de Talca',
    tribunales: [
      '1° Juzgado de Letras de Talca',
      '2° Juzgado de Letras de Talca',
      '3° Juzgado de Letras de Talca',
      '4° Juzgado de Letras de Talca',
      'Juzgado de Letras de Constitución',
      'Juzgado de Letras y Gar. de Curepto',
      '1° Juzgado de Letras de Curicó',
      '2° Juzgado de Letras de Curicó',
      '2° Juzgado de Letras de Curicó exp 3°',
      'Juzgado de Letras y Gar. de Licantén',
      'Juzgado de Letras de Molina',
      '1° Juzgado de Letras de Linares',
      '2° Juzgado de Letras de Linares',
      'Juzgado de Letras de San Javier',
      'Juzgado de Letras de Cauquenes',
      'Juzgado de Letras y Gar. de Chanco',
      'Juzgado de Letras de Parral',
    ],
  },
  {
    corte: 'C.A. de Chillán',
    tribunales: [
      '1° Juzgado Civil de Chillán',
      '2° Juzgado Civil de Chillán',
      '1° Juzgado de Letras de San Carlos',
      'Juzgado de Letras de Yungay',
      'Juzgado de Letras y Gar. de Bulnes',
      'Juzgado de Letras y Gar. de Coelemu',
      'Juzgado de Letras y Gar. de Quirihue',
    ],
  },
  {
    corte: 'C.A. de Concepción',
    tribunales: [
      '1° Juzgado de Letras de Los Angeles',
      '2° Juzgado de Letras de Los Angeles',
      '2° Juzgado de Letras de Los Angeles exp 3°',
      'Juzgado de Letras y Gar. de Mulchen',
      'Juzgado de Letras y Gar. de Nacimiento',
      'Juzgado de Letras y Gar. de Laja',
      'Juzgado de Letras y Gar. de Yumbel',
      '1° Juzgado Civil de Concepción',
      '2° Juzgado Civil de Concepción',
      '3° Juzgado Civil de Concepción',
      '1° Juzgado Civil de Talcahuano',
      '2° Juzgado Civil de Talcahuano',
      'Juzgado de Letras de Tomé',
      'Juzgado de Letras y Gar. de Florida',
      'Juzgado de Letras y Gar. de Santa Juana',
      'Juzgado de Letras y Gar. de Lota',
      '1° Juzgado de Letras de Coronel',
      '2° Juzgado de Letras de Coronel',
      'Juzgado de Letras y Gar. de Lebu',
    ],
  },
  {
    corte: 'C.A. de Temuco',
    tribunales: [
      '1° Juzgado Civil de Temuco',
      '2° Juzgado Civil de Temuco',
      'Juzgado de Letras de Angol',
      'Juzgado de Letras y Gar. de Collipulli',
      'Juzgado de Letras y Gar. de Traiguén',
      'Juzgado de Letras de Victoria',
      'Juzgado de Letras y Gar. de Curacautín',
      'Juzgado de Letras Loncoche',
      'Juzgado de Letras de Pitrufquen',
      'Juzgado de Letras de Villarrica',
      'Juzgado de Letras de Nueva Imperial',
      'Juzgado de Letras y Gar. de Pucón',
      'Juzgado de Letras de Lautaro',
      'Juzgado de Letras y Gar. de Carahue',
      '3° Juzgado Civil de Temuco',
      'Juzgado de Letras y Gar. de Toltén',
      'Juzgado de Letras y Gar. de Purén',
    ],
  },
  {
    corte: 'C.A. de Valdivia',
    tribunales: [
      '1° Juzgado Civil de Valdivia',
      '2° Juzgado Civil de Valdivia',
      'Juzgado de Letras de Mariquina',
      'Juzgado de Letras y Gar. de Paillaco',
      'Juzgado de Letras Los Lagos',
      'Juzgado de Letras y Gar. de Panguipulli',
      'Juzgado de Letras y Gar. de la Unión',
      'Juzgado de Letras y Gar. de Río Bueno',
      '1° Juzgado de Letras de Osorno',
      '2° Juzgado de Letras de Osorno',
      'Juzgado de Letras de Rio Negro',
    ],
  },
  {
    corte: 'C.A. de Puerto Montt',
    tribunales: [
      '1° Juzgado Civil de Puerto Montt',
      '2° Juzgado Civil de Puerto Montt',
      'Juzgado de Letras de Puerto Varas',
      'Juzgado de Letras y Gar. de Calbuco',
      'Juzgado de Letras y Gar. de Maullín',
      'Juzgado de Letras de Castro',
      'Juzgado de Letras de Ancud',
      'Juzgado de Letras y Garantía de Achao',
      'Juzgado de Letras y Gar. de Chaitén',
      'Juzgado de Letras y Gar. de Los Muermos',
      'Juzgado de Letras y Gar. de Quellón',
      'Juzgado de Letras y Gar. de Hualaihue',
    ],
  },
  {
    corte: 'C.A. de Coyhaique',
    tribunales: [
      '1° Juzgado de Letras de Coyhaique',
      '1° Juzgado de Letras de Coyhaique ex 2°',
      'Juzgado de Letras y Gar. de Pto. Aysén',
      'Juzgado de Letras y Gar. de Chile Chico',
      'Juzgado de Letras y Gar. de Cochrane',
      'Juzgado de Letras y Gar. de Puerto Cisnes',
    ],
  },
  {
    corte: 'C.A. de Punta Arenas',
    tribunales: [
      '1° Juzgado de Letras de Punta Arenas',
      '2° Juzgado de Letras de Punta Arenas',
      '3° Juzgado de Letras de Punta Arenas',
      'Juzgado de Letras y Gar. de Puerto Natales',
      'Juzgado de Letras y Gar. de Porvenir',
      'Juzgado de Letras y Garantía de Cabo de Hornos',
    ],
  },
  {
    corte: 'C.A. de Santiago',
    tribunales: [
      '1° Juzgado Civil de Santiago',
      '2° Juzgado Civil de Santiago',
      '3° Juzgado Civil de Santiago',
      '4° Juzgado Civil de Santiago',
      '5° Juzgado Civil de Santiago',
      '6° Juzgado Civil de Santiago',
      '7° Juzgado Civil de Santiago',
      '8° Juzgado Civil de Santiago',
      '9° Juzgado Civil de Santiago',
      '10° Juzgado Civil de Santiago',
      '11° Juzgado Civil de Santiago',
      '12° Juzgado Civil de Santiago',
      '13° Juzgado Civil de Santiago',
      '14° Juzgado Civil de Santiago',
      '15° Juzgado Civil de Santiago',
      '16° Juzgado Civil de Santiago',
      '17° Juzgado Civil de Santiago',
      '18° Juzgado Civil de Santiago',
      '19° Juzgado Civil de Santiago',
      '20° Juzgado Civil de Santiago',
      '21° Juzgado Civil de Santiago',
      '22° Juzgado Civil de Santiago',
      '23° Juzgado Civil de Santiago',
      '24° Juzgado Civil de Santiago',
      '25° Juzgado Civil de Santiago',
      '26° Juzgado Civil de Santiago',
      '27° Juzgado Civil de Santiago',
      '28° Juzgado Civil de Santiago',
      '29° Juzgado Civil de Santiago',
      '30° Juzgado Civil de Santiago',
      'Juzgado de Letras de Colina',
    ],
  },
  {
    corte: 'C.A. de San Miguel',
    tribunales: [
      '1° Juzgado Civil de San Miguel',
      '2° Juzgado Civil de San Miguel',
      '3° Juzgado Civil de San Miguel',
      '4° Juzgado Civil de San Miguel',
      '1° Juzgado Civil de Puente Alto',
      '1° Juzgado de Letras de Talagante',
      '2° Juzgado de Letras de Talagante',
      '1° Juzgado de Letras de Melipilla',
      '1° Juzgado de Letras de Buin',
      '2° Juzgado de Letras de Buin',
      'Juzgado de Letras de Peñaflor',
      '1° Juzgado de Letras de San Bernardo',
      '1° Juzgado de Letras de San Bernardo ex 3°',
      '2° Juzgado de Letras de San Bernardo',
      '2° Juzgado de Letras de San Bernardo ex 3°',
    ],
  },
]
